### PR TITLE
Homeworks 4, 5, and 6

### PR DESCRIPTION
**Pull request by cecily-li**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Changes to SQL file for homework 4, created a new file for submission of homework 6 reflection. 

## What did you learn from the changes you have made?
There are multiple ways to approach the same problem and arrive at the same answer, but there are also more concise ways to present the output that may be better for the end user. 

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
N/A

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
N/A

## How were these changes tested?
I tested the sql queries I wrote in a separate sql file before pasting them into my responses.

## A reference to a related issue in your repository (if applicable)
N/A

## Checklist
- [ x] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by amanda-ng518 — APPROVED** [review]
HW6: 8/8

**Review by amanda-ng518 — APPROVED** [review]
HW4: 8/8

**Review by amanda-ng518 — CHANGES_REQUESTED** [review]
HW5: incomplete

**Comment by cecily-li** [comment]
> HW5: incomplete

@amanda-ng518 HW 5 added

**Review by amanda-ng518 — COMMENTED** [review]
HW5: HW5: 8/8
INSERT Q2
INSERT INTO product_units (product_id, product_name,
product_size, product_category_id, product_qty_type, snapshot_timestamp)
SELECT
product_id,
product_name,
product_size,
product_category_id,
product_qty_type,
CURRENT_TIMESTAMP
FROM product AS p
WHERE product_id = 7

DELETE Q1
WITH older_record AS
(SELECT product_id
,MIN(snapshot_timestamp) AS snapshot_timestamp
FROM product_units
WHERE product_id = 7)
DELETE FROM product_units
WHERE (product_id =
(SELECT product_id
FROM older_record
)
AND snapshot_timestamp =
(SELECT snapshot_timestamp
FROM older_record
))

UPDATE Q1
ALTER TABLE product_units
ADD current_quantity INT;
UPDATE product_units
SET current_quantity = (
SELECT current_quantity
FROM (
SELECT p.product_id, COALESCE(quantity,0) as current_quantity
FROM product_units p
LEFT JOIN (
SELECT *
,ROW_NUMBER() OVER( PARTITION BY vi.product_id ORDER BY market_date DESC) AS rn
FROM vendor_inventory vi
) vi ON p.product_id = vi.product_id
WHERE rn = 1
OR rn IS NULL
) p
WHERE product_units.product_id = p.product_id);

**Pull request merged**
